/*
Copyright © 2021 Luqman Mohammed m.luqman077@gmail.com

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/luqmanMohammed/eventsrunner/crd/pkg/apis/eventsrunner.io/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RunnerLister helps list Runners.
// All objects returned here must be treated as read-only.
type RunnerLister interface {
	// List lists all Runners in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Runner, err error)
	// Runners returns an object that can list and get Runners.
	Runners(namespace string) RunnerNamespaceLister
	RunnerListerExpansion
}

// runnerLister implements the RunnerLister interface.
type runnerLister struct {
	indexer cache.Indexer
}

// NewRunnerLister returns a new RunnerLister.
func NewRunnerLister(indexer cache.Indexer) RunnerLister {
	return &runnerLister{indexer: indexer}
}

// List lists all Runners in the indexer.
func (s *runnerLister) List(selector labels.Selector) (ret []*v1alpha1.Runner, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Runner))
	})
	return ret, err
}

// Runners returns an object that can list and get Runners.
func (s *runnerLister) Runners(namespace string) RunnerNamespaceLister {
	return runnerNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RunnerNamespaceLister helps list and get Runners.
// All objects returned here must be treated as read-only.
type RunnerNamespaceLister interface {
	// List lists all Runners in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Runner, err error)
	// Get retrieves the Runner from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Runner, error)
	RunnerNamespaceListerExpansion
}

// runnerNamespaceLister implements the RunnerNamespaceLister
// interface.
type runnerNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Runners in the indexer for a given namespace.
func (s runnerNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.Runner, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Runner))
	})
	return ret, err
}

// Get retrieves the Runner from the indexer for a given namespace and name.
func (s runnerNamespaceLister) Get(name string) (*v1alpha1.Runner, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("runner"), name)
	}
	return obj.(*v1alpha1.Runner), nil
}
