/*
Copyright © 2021 Luqman Mohammed m.luqman077@gmail.com

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/luqmanMohammed/eventsrunner/crd/pkg/apis/eventsrunner.io/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RunnerBindingLister helps list RunnerBindings.
// All objects returned here must be treated as read-only.
type RunnerBindingLister interface {
	// List lists all RunnerBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RunnerBinding, err error)
	// RunnerBindings returns an object that can list and get RunnerBindings.
	RunnerBindings(namespace string) RunnerBindingNamespaceLister
	RunnerBindingListerExpansion
}

// runnerBindingLister implements the RunnerBindingLister interface.
type runnerBindingLister struct {
	indexer cache.Indexer
}

// NewRunnerBindingLister returns a new RunnerBindingLister.
func NewRunnerBindingLister(indexer cache.Indexer) RunnerBindingLister {
	return &runnerBindingLister{indexer: indexer}
}

// List lists all RunnerBindings in the indexer.
func (s *runnerBindingLister) List(selector labels.Selector) (ret []*v1alpha1.RunnerBinding, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RunnerBinding))
	})
	return ret, err
}

// RunnerBindings returns an object that can list and get RunnerBindings.
func (s *runnerBindingLister) RunnerBindings(namespace string) RunnerBindingNamespaceLister {
	return runnerBindingNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RunnerBindingNamespaceLister helps list and get RunnerBindings.
// All objects returned here must be treated as read-only.
type RunnerBindingNamespaceLister interface {
	// List lists all RunnerBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RunnerBinding, err error)
	// Get retrieves the RunnerBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.RunnerBinding, error)
	RunnerBindingNamespaceListerExpansion
}

// runnerBindingNamespaceLister implements the RunnerBindingNamespaceLister
// interface.
type runnerBindingNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RunnerBindings in the indexer for a given namespace.
func (s runnerBindingNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.RunnerBinding, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RunnerBinding))
	})
	return ret, err
}

// Get retrieves the RunnerBinding from the indexer for a given namespace and name.
func (s runnerBindingNamespaceLister) Get(name string) (*v1alpha1.RunnerBinding, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("runnerbinding"), name)
	}
	return obj.(*v1alpha1.RunnerBinding), nil
}
