apiVersion: eventsrunner.io/v1alpha1
kind: Runner
metadata:
  name: runner-sample
  namespace: eventsrunner
  labels:
    eventsrunner.io/identifier: eventsrunner
spec:
  metadata:
    labels:
      test: test
  spec:
    restartPolicy: Never
    containers:
      - name: test
        image: busybox
