/*
Copyright © 2021 Luqman Mohammed m.luqman077@gmail.com

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/luqmanMohammed/eventsrunner/crd/pkg/apis/eventsrunner.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRunners implements RunnerInterface
type FakeRunners struct {
	Fake *FakeEventsrunnerV1alpha1
	ns   string
}

var runnersResource = schema.GroupVersionResource{Group: "eventsrunner.io", Version: "v1alpha1", Resource: "runners"}

var runnersKind = schema.GroupVersionKind{Group: "eventsrunner.io", Version: "v1alpha1", Kind: "Runner"}

// Get takes name of the runner, and returns the corresponding runner object, and an error if there is any.
func (c *FakeRunners) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Runner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(runnersResource, c.ns, name), &v1alpha1.Runner{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Runner), err
}

// List takes label and field selectors, and returns the list of Runners that match those selectors.
func (c *FakeRunners) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RunnerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(runnersResource, runnersKind, c.ns, opts), &v1alpha1.RunnerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RunnerList{ListMeta: obj.(*v1alpha1.RunnerList).ListMeta}
	for _, item := range obj.(*v1alpha1.RunnerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested runners.
func (c *FakeRunners) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(runnersResource, c.ns, opts))

}

// Create takes the representation of a runner and creates it.  Returns the server's representation of the runner, and an error, if there is any.
func (c *FakeRunners) Create(ctx context.Context, runner *v1alpha1.Runner, opts v1.CreateOptions) (result *v1alpha1.Runner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(runnersResource, c.ns, runner), &v1alpha1.Runner{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Runner), err
}

// Update takes the representation of a runner and updates it. Returns the server's representation of the runner, and an error, if there is any.
func (c *FakeRunners) Update(ctx context.Context, runner *v1alpha1.Runner, opts v1.UpdateOptions) (result *v1alpha1.Runner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(runnersResource, c.ns, runner), &v1alpha1.Runner{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Runner), err
}

// Delete takes name of the runner and deletes it. Returns an error if one occurs.
func (c *FakeRunners) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(runnersResource, c.ns, name, opts), &v1alpha1.Runner{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRunners) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(runnersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RunnerList{})
	return err
}

// Patch applies the patch and returns the patched runner.
func (c *FakeRunners) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Runner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(runnersResource, c.ns, name, pt, data, subresources...), &v1alpha1.Runner{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Runner), err
}
