/*
Copyright © 2021 Luqman Mohammed m.luqman077@gmail.com

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/luqmanMohammed/eventsrunner/ereventcrd/pkg/apis/eventsrunner.io/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// EREventLister helps list EREvents.
// All objects returned here must be treated as read-only.
type EREventLister interface {
	// List lists all EREvents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.EREvent, err error)
	// EREvents returns an object that can list and get EREvents.
	EREvents(namespace string) EREventNamespaceLister
	EREventListerExpansion
}

// eREventLister implements the EREventLister interface.
type eREventLister struct {
	indexer cache.Indexer
}

// NewEREventLister returns a new EREventLister.
func NewEREventLister(indexer cache.Indexer) EREventLister {
	return &eREventLister{indexer: indexer}
}

// List lists all EREvents in the indexer.
func (s *eREventLister) List(selector labels.Selector) (ret []*v1alpha1.EREvent, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.EREvent))
	})
	return ret, err
}

// EREvents returns an object that can list and get EREvents.
func (s *eREventLister) EREvents(namespace string) EREventNamespaceLister {
	return eREventNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// EREventNamespaceLister helps list and get EREvents.
// All objects returned here must be treated as read-only.
type EREventNamespaceLister interface {
	// List lists all EREvents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.EREvent, err error)
	// Get retrieves the EREvent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.EREvent, error)
	EREventNamespaceListerExpansion
}

// eREventNamespaceLister implements the EREventNamespaceLister
// interface.
type eREventNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all EREvents in the indexer for a given namespace.
func (s eREventNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.EREvent, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.EREvent))
	})
	return ret, err
}

// Get retrieves the EREvent from the indexer for a given namespace and name.
func (s eREventNamespaceLister) Get(name string) (*v1alpha1.EREvent, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("erevent"), name)
	}
	return obj.(*v1alpha1.EREvent), nil
}
