# permissions for end users to view runnerbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runnerbinding-viewer-role
rules:
- apiGroups:
  - eventsrunner.io
  resources:
  - runnerbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eventsrunner.io
  resources:
  - runnerbindings/status
  verbs:
  - get
