# permissions for end users to edit rulesopts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rulesopts-editor-role
rules:
- apiGroups:
  - eventsrunner.io
  resources:
  - rulesopts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventsrunner.io
  resources:
  - rulesopts/status
  verbs:
  - get
