# permissions for end users to edit runnerbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runnerbinding-editor-role
rules:
- apiGroups:
  - eventsrunner.io
  resources:
  - runnerbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventsrunner.io
  resources:
  - runnerbindings/status
  verbs:
  - get
