/*
Copyright © 2021 Luqman Mohammed m.luqman077@gmail.com

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/luqmanMohammed/eventsrunner/ereventcrd/pkg/apis/eventsrunner.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEREvents implements EREventInterface
type FakeEREvents struct {
	Fake *FakeEventsrunnerV1alpha1
	ns   string
}

var ereventsResource = schema.GroupVersionResource{Group: "eventsrunner.io", Version: "v1alpha1", Resource: "erevents"}

var ereventsKind = schema.GroupVersionKind{Group: "eventsrunner.io", Version: "v1alpha1", Kind: "EREvent"}

// Get takes name of the eREvent, and returns the corresponding eREvent object, and an error if there is any.
func (c *FakeEREvents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.EREvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ereventsResource, c.ns, name), &v1alpha1.EREvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EREvent), err
}

// List takes label and field selectors, and returns the list of EREvents that match those selectors.
func (c *FakeEREvents) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EREventList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ereventsResource, ereventsKind, c.ns, opts), &v1alpha1.EREventList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EREventList{ListMeta: obj.(*v1alpha1.EREventList).ListMeta}
	for _, item := range obj.(*v1alpha1.EREventList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested eREvents.
func (c *FakeEREvents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ereventsResource, c.ns, opts))

}

// Create takes the representation of a eREvent and creates it.  Returns the server's representation of the eREvent, and an error, if there is any.
func (c *FakeEREvents) Create(ctx context.Context, eREvent *v1alpha1.EREvent, opts v1.CreateOptions) (result *v1alpha1.EREvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ereventsResource, c.ns, eREvent), &v1alpha1.EREvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EREvent), err
}

// Update takes the representation of a eREvent and updates it. Returns the server's representation of the eREvent, and an error, if there is any.
func (c *FakeEREvents) Update(ctx context.Context, eREvent *v1alpha1.EREvent, opts v1.UpdateOptions) (result *v1alpha1.EREvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ereventsResource, c.ns, eREvent), &v1alpha1.EREvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EREvent), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEREvents) UpdateStatus(ctx context.Context, eREvent *v1alpha1.EREvent, opts v1.UpdateOptions) (*v1alpha1.EREvent, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ereventsResource, "status", c.ns, eREvent), &v1alpha1.EREvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EREvent), err
}

// Delete takes name of the eREvent and deletes it. Returns an error if one occurs.
func (c *FakeEREvents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(ereventsResource, c.ns, name, opts), &v1alpha1.EREvent{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEREvents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ereventsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.EREventList{})
	return err
}

// Patch applies the patch and returns the patched eREvent.
func (c *FakeEREvents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EREvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ereventsResource, c.ns, name, pt, data, subresources...), &v1alpha1.EREvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EREvent), err
}
